### PR TITLE
fixed Travis, converted README and version as file

### PR DESCRIPTION
**Pull request by StrikerRUS**
### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [x] I have added tests that prove my fix is effective or that my feature works
- [n/a] I have added necessary documentation about the functionality in the appropriate .md file
- [n/a] I have added in line documentation to the code I modified

### Short description of what this PR does:
~- fix tests and coverage by removing the check of existence of `Dockerfile`, `docker-compose.yml`, `USE_CASES.md` and using only codecov for coverage.~
- add  `VERSION.txt` file, so in the future version should be incremented only in this file.
- convert `README.md` to `README.rst` (appearance can be checked in this branch https://github.com/StrikerRUS/open-source-library-data-collector/blob/pypi/README.rst), so `fix_README.py` and `register.py` are not needed anymore.
- add Python versions badge.
   
- add PyPI version badge.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/open-source-library-data-collector?pullRequest=138) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/open-source-library-data-collector?pullRequest=138) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/open-source-library-data-collector?pullRequest=138) it.</sub>

**Comment by StrikerRUS** [comment]
Hi @thinkingserious !
You've asked me in https://github.com/sendgrid/python-http-client/pull/93#issuecomment-428022147 to propose those changes in other SendGrid repos. This is the last one. Due to the `README` file replacement this PR has many conflicts with other open PRs. Is it possible to merge it first to avoid multiple branch rebases?

**Comment by StrikerRUS** [comment]
ping @thinkingserious

**Comment by StrikerRUS** [comment]
Closed due to the disinterest.

**Pull request closed without merging**
