### PR TITLE
Update .env_sample

### PR DESCRIPTION
**Pull request by Deborah-Digges**
`open_source_external_library_data` is the name given in the create statement in the instructions, so we should be consistent with that name here as well.

# Fixes # 

### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation about the functionality in the appropriate .md file
- [x] I have added in line documentation to the code I modified

### Short description of what this PR does:
- open_source_external_library_data is the name given in the create database statement in the instructions(`CREATE DATABASE IF NOT EXISTS open_source_external_library_data`), so we should be consistent with that name here as well.

If you have questions, please send an email to [Sendgrid](mailto:dx@sendgrid.com), or file a Github Issue in this repository.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/open-source-library-data-collector?pullRequest=141) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/open-source-library-data-collector?pullRequest=141) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/open-source-library-data-collector?pullRequest=141) it.</sub>

**Comment by Deborah-Digges** [comment]
Fixes #142

**Comment by thinkingserious** [comment]
Hello @Deborah-Digges,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by Deborah-Digges** [comment]
Yay :D :D thank you, Team SendGrid 🏆

**Pull request merged**
