### PR TITLE
Change deprecated link

### LINKED ISSUE #124: Update DB to include new SendGrid Node.js libraries
https://www.npmjs.com/org/sendgrid

### PR DESCRIPTION
**Pull request by gabrielgene**
# Fixes # 

Closes #124 
### Checklist
- [n/a] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [n/a] I have added tests that prove my fix is effective or that my feature works
- [n/a] I have added necessary documentation about the functionality in the appropriate .md file
- [n/a] I have added in line documentation to the code I modified

### Short description of what this PR does:
- Change deprecated link 

If you have questions, please send an email to [Sendgrid](mailto:dx@sendgrid.com), or file a Github Issue in this repository.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/open-source-library-data-collector?pullRequest=136) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/open-source-library-data-collector?pullRequest=136) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/open-source-library-data-collector?pullRequest=136) it.</sub>

**Comment by gabrielgene** [comment]
Hey @thinkingserious I dont know I tests broken.

**Comment by gabrielgene** [comment]
@agnesjang98 Can you help me ?

**Comment by agnesjang98** [comment]
Hi @gabrielgene I will take a look!

**Comment by agnesjang98** [comment]
@gabrielgene I updated your forked branch to have the latest updates from master branch, and waiting to see if that will make a difference for the build. In the meantime, can you sign the CLA? Thanks!

**Comment by gabrielgene** [comment]
Thanks @agnesjang98 :smile:

**Comment by gabrielgene** [comment]
Hey @agnesjang98 can you review and merge this ?

**Comment by gabrielgene** [comment]
Ping :) @thinkingserious @agnesjang98

**Pull request closed without merging**
